services:
  authentication:
    build:
      context: .
      dockerfile: Authentication/Dockerfile
    container_name: Authentication
    environment:
    - RABBITMQ_HOST=RABBITMQ_HOST
    - RABBITMQ_PORT=RABBITMQ_PORT

  spot:
    build:
      context: .
      dockerfile: SpotService/Dockerfile
    container_name: SpotService
    environment:
    - RABBITMQ_HOST=RABBITMQ_HOST
    - RABBITMQ_PORT=RABBITMQ_PORT