services:
  rabbit:
    image: rabbitmq:3-management
    container_name: rabbit
    ports:
      - 15672:15672
      - 5672:5672

  configuration:
    build: 
      context: .
      dockerfile: ConfigurationService/ConfigurationService/Dockerfile
    container_name: 'configuration'
    environment:
      - RABBITMQ_HOST=RABBITMQ_HOST
      - RABBITMQ_PORT=RABBITMQ_PORT
    ports:
      - 8081:8081
      - 8080:8080
  
  eureka:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - 8761:8761

  image:
    build:
      context: .
      dockerfile: ImageService/Dockerfile
    container_name: ImageService
    environment:
      - RABBITMQ_HOST=RABBITMQ_HOST
      - RABBITMQ_PORT=RABBITMQ_PORT
