-- Auto-generated SQL script #202410171617
TRUNCATE TABLE TRIP_BUDDY.SPOT.CONSTANT;
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'AF',N'ATR_CONTINENT',N'Africa');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'AS',N'ATR_CONTINENT',N'Asia');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'EU',N'ATR_CONTINENT',N'Europe');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'NA',N'ATR_CONTINENT',N'North America');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'SA',N'ATR_CONTINENT',N'South America');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'AU',N'ATR_CONTINENT',N'Australia ');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'SA',N'AS_SUB_CONTINENT',N'South Asia');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'SEA',N'AS_SUB_CONTINENT',N'Southeast Asia');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'EA',N'AS_SUB_CONTINENT',N'East Asia');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'WA',N'AS_SUB_CONTINENT',N'West Asia');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'CA',N'AS_SUB_CONTINENT',N'Central Asia');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'SE',N'EU_SUB_CONTINENT',N'Southern Europe');
INSERT INTO TRIP_BUDDY.SPOT.CONSTANT (CONSTANT_CODE,CONSTANT_TYPE,CONSTANT_NAME)
	VALUES (N'NE',N'EU_SUB_CONTINENT',N'Northern Europe');
