server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    server:
      enableSelfPreservation: false
  instance:
    evictionIntervalMs: 60000 # 1 minutes
    leaseRenewalIntervalInSeconds: 30 # 30 seconds